add index.html file license.txt file js directory css directory babel…
olawale-o/tribute-page pull request #1
Opened 2021-06-02 08:55 UTC by olawale-o

… directory

2021-06-02 09:16 UTC, olawale-o commented
Hi **olawale-o**
You followed the github flow in the project setup.

I think there are some issues you still need to work on
![screen](https://user-images.githubusercontent.com/55432600/120452994-8c332f80-c38a-11eb-99a0-30e7e455fca9.png)

Your pull request title is too verbose and the descriptive message about what changes you made to your pull is not clear enough, i would suggest you include the microverse linters specification to your project  [check out this link](https://github.com/microverseinc/linters-config).

2021-06-02 09:23 UTC, olawale-o commented on index.html
> +<!DOCTYPE html>
I would suggest you make use of [html semantic tags](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) and read up on [html best pratices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2021-06-02 09:24 UTC, olawale-o commented on index.html
> +</html>
I would suggest you make use of [html semantic tags](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) and read up on [html best pratices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2021-06-02 16:10 UTC, acushlakoncept requested changes
Hi @olawale-o,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

In your summary about PR title and a linter, I think it would be nice to separate it into different paragraphs for readability and clarity. Again WHY they should make those changes becomes very vital so it does not appear you are simply issuing a command.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Let's always start by following the "Request changes" template. I think this will help keep your request organized.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-02 16:10 UTC, acushlakoncept commented on index.html
> +</html>
Nice job on how you suggested the use of semantic tags with pointers 👍🏽
I think you should also give reasons WHY you're encouraging them to use semantic tags as this will give the student more insight and conviction on making the requested changes.

2021-06-03 00:16 UTC, Spayco approved these changes
Hi @olawale-o, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-03 01:41 UTC, merged